### ISSUE TITLE
Drop the dependency on ppx

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/configurator#2]
configurator seems like a quite low level package that is useful in many situations where ppx isn't desirable (low dep footprint) or available (windows, some rare BSD's). Would it be possible to get rid of the few minor uses of ppx in configurator?

Seems like there's only a couple of simple uses of ppx_sexp_conv and ppx_compare. It would  be easy enough to write those out manually. Or if something more future proof is necessary, perhaps implement the same system that base uses?

**Comment by hhugo** [comment]
There are no more dependencies on ppx
